---
sudo: required

env: 
  - distro: centos7
    init: /usr/lib/systemd/systemd
    run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"


services:        
  - docker

before_install:
  - 'docker pull geerlingguy/docker-${distro}-ansible:latest'

script:
  - container_id=$(mktemp) 
  - ls ./../
  - pwd  
  - ls
  - 'docker run --detach --volume="./../":/etc/ansible/roles/role_under_test:ro ${run_opts} geerlingguy/docker-${distro}-ansible:latest "${init}" > "${container_id}"'
   
  - role_name=$(basename $(pwd))  
    #Check syntax 
  - >
    docker exec "$(cat ${container_id})" env TERM=xterm     
    ansible-playbook /etc/ansible/roles/role_under_test/${role_name}/tests/test.yml
    --syntax-check
   
    #First run playbook  
  - >
    docker exec "$(cat ${container_id})" env TERM=xterm     
    ansible-playbook /etc/ansible/roles/role_under_test/${role_name}/tests/test.yml
  
    #Idempotence test
  - idempotence=$(mktemp)  
  - >
    docker exec "$(cat ${container_id})" env TERM=xterm     
    ansible-playbook /etc/ansible/roles/role_under_test/${role_name}/tests/test.yml
    | tee -a ${idempotence}

  - >
    tail ${idempotence} 
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

  - >
    docker exec "$(cat ${container_id})" env TERM=xterm mysql --version      
          
notifications:
